# Generated by Django 3.0.8 on 2020-12-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
